spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agilebpm_5?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    com:
      baomidou: DEBUG